package levels

var levelLayouts = map[int][]string{
	0: {
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
    },
	1: {
        "               ",
        " b b  b b  b b ",
        " b b  b b  b b ",
        " b b  bbb  b b ",
        " b b  b b  b b ",
        " b b       b b ",
        "      b b      ",
        "b bbb     bbb b",
        "      b b      ",
        "      bbb      ",
        " b b  b b  b b ",
        " b b  b b  b b ",
        " b b       b b ",
		" b b  bbb  b b ",
		"      beb      ",
    },
    2: {
		"               ",
		"  bb    b   f  ",
		"        b      ",
		" bcc   bb  b b ",
		"   b  ccc  bbb ",
		"   b   b   b   ",
		"f  b  b    bfbb",
		"ff  cccc    f  ",
		" bbbccb  b  fb ",
		"   b  b  b b b ",
		"bb b  bbbb   b ",
		" b b  bbbbcbbb ",
		" b b      c    ",
		" b    bbb  b b ",
		" b b  beb  bbb ",
    },
    3: {
		"               ",
		"    bbbbbbb    ",
		"   b       b   ",
		"  b    c    b   ",
		"  b    c    b  ",
		"   bb     bb   ",
		"     bbbbb     ",
		" ff    f     f ",
		"  fff  f   ff  ",
		"  ffff f ffff  ",
		"    fffffff    ",
		"      fff      ",
		"       f       ",
		"      bbb      ",
		"ww    beb    ww",
    },
    4: {
		"               ",
		"               ",
		"   bb     bb   ",
		"  b    b    b  ",
		" b           b ",
		"     bbbbb     ",
		"f    bcccb    f",
		"www  ccccc  www",
		"f    ccccc    f",
		"f    bcccb    f",
		"               ",
		"bbbb       bbbb",
		"   b       b   ",
		"      bbb      ",
		"      beb      ",
    },
	5: {
		"               ",
		"   bbbbbbbb    ",
		"  bbb     bbb  ",
		" bbb       bbb ",
		" bb         bb ",
		" bb         bb ",
		" bb         bb ",
		" bb  b   b  bb ",
		" bb         bb ",
		"bb    ccc    bb",
		"bb     c     bb",
		"bb           bb",
		"b             b",
		" ccc  bbb  ccc ",
		" ccc  beb  ccc ",
    },
	6: {
		"               ",
		"     fbbf   f  ",
		"     bbbb   f  ",
		" fbf bbbb      ",
		"     fbbf   fbb",
		"               ",
		"bf      c      ",
		"      ccc fbbf ",
		" fbbf c   bbbb ",
		" bbbb     bbbb ",
		" bbbb  c  fbbf ",
		" fbbf  cc   c  ",
		"  c         c  ",
		" ccc  bbb   c  ",
		"  c   beb      ",
    },
	7: {
		"               ",
		"     b  f  b   ",
		"    b  f  b    ",
		"   b  f  b   ww",
		"  b  f  b      ",
		" b  f  b   b   ",
		"   f  b  c  b  ",
		"  f  b    c  b ",
		" f  b   b  c   ",
		"   b     b  c  ",
		"  b    w  b  c ",
		" b    www  b   ",
		"            b  ",
		"ww    bbb    b ",
		"      beb      ",
    },
	8: {
		"fffffffffffffff",
		"ff  fff  ff fff",
		"               ",
		"               ",
		"              f",
		"          ww ww",
		"    c     wc cc",
		"    ww wwwwc  b",
		"    wf  cc     ",
		"f   w     bbb  ",
		"www w bb       ",
		"ccc            ",
		"bb   ccccc     ",
		"     cbbbc     ",
		"     cbebc   ff",
    },
	9: {
		"     c   c     ",
		"      c c      ",
		"  bbb  c  bbb  ",
		" b   b c b   b ",
		" b w  bcb  w b ",
		"  b    b    b  ",
		"   b c   c b   ",
		"  b         b  ",
		" b  c  c  c  b ",
		" b           b ",
		" b  f  b  f  b ",
		"  b   b b   b  ",
		"   bbb   bbb   ",
		"      bbb      ",
		"      beb      ",
	},
	10: {
		"               ",
		"        f   b  ",
		"        b      ",
		"   wb          ",
		"          cbc  ",
		"               ",
		" b             ",
		" f      bc     ",
		"               ",
		"    bc     cb  ",
		"               ",
		"  c       bc   ",
		" wb            ",
		"      bbb      ",
		"      beb      ",
    },
	99: {
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"               ",
		"      bbb      ",
		"      beb      ",
    },
}


func GetLevelLayout(levelNumber int) []string {
    if layout, ok := levelLayouts[levelNumber]; ok {

        return layout
    }

    // Return empty layout to handle the case when the level number is not found
    return []string{}
}
